import { motion } from "framer-motion";
import { Bot, Users, Wallet } from "lucide-react";
import { FeatureCard } from "./FeatureCard";

const workforceFeatures = [
  {
    icon: <Bot className="w-12 h-12 text-primary mb-4" />,
    title: "24/7 Operation",
    description: "Tireless AI agents working around the clock to identify and capitalize on opportunities."
  },
  {
    icon: <Users className="w-12 h-12 text-primary mb-4" />,
    title: "Collective Intelligence",
    description: "Multiple specialized agents collaborating to maximize value creation for holders."
  },
  {
    icon: <Wallet className="w-12 h-12 text-primary mb-4" />,
    title: "Holder Benefits",
    description: "All value generated by the autonomous workforce directly benefits token holders."
  }
];

export const AutonomousWorkforce = () => {
  return (
    <section className="py-24 relative overflow-hidden bg-dark-lighter">
      <div className="absolute inset-0 swarm-grid opacity-20" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-secondary/10 to-transparent opacity-90" />
      
      <div className="container mx-auto px-4 relative">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          className="max-w-3xl mx-auto text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-8">
            <span className="gradient-text">Autonomous Workforce</span>
          </h2>
          <p className="text-lg md:text-xl text-gray-300 leading-relaxed">
            A tireless team of AI agents working 24/7 to generate value exclusively for SWARM token holders.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {workforceFeatures.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.2 }}
            >
              <FeatureCard feature={feature} />
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};