import { motion } from "framer-motion";
import { Award, DollarSign, Network, HandShake, UserPlus, Shield, Rocket } from "lucide-react";

export const BenefitsSection = () => {
  const benefits = [
    {
      icon: <DollarSign className="w-12 h-12 text-primary mb-4" />,
      title: "Revenue Share",
      description: "Direct share of profits generated by AI agent operations across multiple chains"
    },
    {
      icon: <Network className="w-12 h-12 text-primary mb-4" />,
      title: "Network Access",
      description: "Priority access to SWARM's network of autonomous AI agents and their capabilities"
    },
    {
      icon: <Award className="w-12 h-12 text-primary mb-4" />,
      title: "Early Access",
      description: "First access to new AI agent features and network upgrades"
    },
    {
      icon: <HandShake className="w-12 h-12 text-primary mb-4" />,
      title: "Governance Rights",
      description: "Participate in key decisions about the network's development and operation"
    },
    {
      icon: <Shield className="w-12 h-12 text-primary mb-4" />,
      title: "Protected Returns",
      description: "Benefit from automated risk management and security protocols"
    },
    {
      icon: <Rocket className="w-12 h-12 text-primary mb-4" />,
      title: "Growth Potential",
      description: "Token value grows with network expansion and increased agent efficiency"
    }
  ];

  return (
    <section className="py-24 bg-dark-lighter relative overflow-hidden">
      <div className="absolute inset-0 swarm-grid opacity-20" />
      <div className="absolute inset-0 bg-gradient-radial from-primary/5 to-transparent opacity-90" />
      
      <div className="container mx-auto px-4 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            <span className="gradient-text">Token Holder Benefits</span>
          </h2>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Holding SWARM tokens grants you access to a suite of benefits powered by our network of autonomous AI agents
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {benefits.map((benefit, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className="bg-dark p-8 rounded-xl border border-primary/20 hover:border-primary/40 transition-all duration-300"
            >
              <div className="flex flex-col items-center text-center">
                {benefit.icon}
                <h3 className="text-xl font-bold mb-3">{benefit.title}</h3>
                <p className="text-gray-300">{benefit.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};