// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjsyqfyjrakfemrwcprr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqc3lxZnlqcmFrZmVtcndjcHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MDQ3MTMsImV4cCI6MjA1MTA4MDcxM30.SPhKTwhfrxJIagAto_zstCpBbTth4OTLZ1LVD17YxeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);